services:
  nginx:
    container_name: nginx
    image: nginx:1.19
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
